## 1. Numpy
### 1.1 Numpy 배열

In [2]:
import numpy as np

- numpy n-dim array(ndarray) vs list

In [5]:
l = [1, 2, 3, 4, 5]
l * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
n = np.array([1, 2, 3, 4, 5])
n * 2

array([ 2,  4,  6,  8, 10])

In [7]:
# 모든 수의 제곱수
[i * i for i in l]

[1, 4, 9, 16, 25]

In [8]:
np.square(n)

array([ 1,  4,  9, 16, 25])

- 1차원 배열(Vector)

In [9]:
a = np.array((1, 2, 3, 4, 5))
type(a)

numpy.ndarray

In [10]:
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (5,), 1, 5)

In [11]:
# 벡터화 연산
a * 2

array([ 2,  4,  6,  8, 10])

In [12]:
b = np.array([10, 20, 30, 40, 50])
c = 2 * a + b
c

array([12, 24, 36, 48, 60])

In [13]:
a == 2

array([False,  True, False, False, False])

In [14]:
b > 20

array([False, False,  True,  True,  True])

- 2차원 배열(Matrix)

In [17]:
c = np.array([[1, 2, 3,], [4, 5, 6]])
c = np.arange(1, 7).reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [18]:
d = np.arange(1, 25).reshape(2, 3, 4)   # plane, row, column
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
d.dtype, d.shape, d.ndim, d.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
a[0], a[3], a[-1]

(1, 4, 5)

In [22]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c[0][0], c[0, 0]

(1, 1)

In [24]:
c[1, 0], c[0, -1], c[-1, -1]

(4, 3, 6)

In [25]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [26]:
# 9, 20
d[0, -1, 0], d[1, 1, -1]

(9, 20)

- 배열의 슬라이싱

In [27]:
# 리스트에서는 행, 열 슬라이싱이 동시에 안됨
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [28]:
# 엉뚱한 결과가 나옴
l[:2][:2]

[[1, 2, 3], [4, 5, 6]]

In [29]:
l[1][:2]

[4, 5]