### 1.3 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산

In [2]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [6]:
%%time
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i]

CPU times: total: 46.9 ms
Wall time: 48 ms


In [8]:
%time z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [10]:
a >= b

array([False,  True,  True,  True])

In [11]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [12]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [13]:
5 * a

array([ 5, 10, 15, 20])

In [14]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [15]:
x = np.arange(1, 5)
np.sum(x)

10

In [16]:
x.sum()

10

In [18]:
x.min(), x.max(), x.mean()          # 최소, 최대, 평균

(1, 4, 2.5)

In [19]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [20]:
# 통계: 분산, 표준편차
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [21]:
# 최소값, 최대값의 인덱스
x.argmin(), x.argmax()

(0, 3)

- all / any

In [22]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [23]:
np.all(a == a)

True

- 2차원 이상의 연산

In [24]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# 모든 원소의 합과 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [28]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 액세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [29]:
# axis = 1, 각 좌표(row, col)에서 col를 변경시켜가면서 액세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [31]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [33]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [34]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [36]:
np.random.seed = 2023
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[3.144 , 9.7014, 9.0352, 0.1313, 6.8468, 9.9635],
       [5.0685, 0.7351, 2.0686, 1.6249, 4.5348, 2.4392],
       [4.5463, 7.7391, 5.2385, 7.4663, 2.204 , 2.1008],
       [5.4089, 6.1444, 4.2074, 4.0773, 7.2275, 3.8665],
       [2.3461, 8.0856, 8.2221, 1.2932, 4.054 , 8.1992]])

- 전체의 최댓값

In [38]:
np.max(x)

9.9635

- 각 행의 합

In [43]:
np.sum(x, axis=1)

array([38.8222, 16.4711, 29.295 , 30.932 , 32.2002])

- 각 행의 최댓값

In [44]:
np.max(x, axis=1)[1]

array([9.9635, 5.0685, 7.7391, 7.2275, 8.2221])

- 각 열의 평균

In [45]:
np.mean(x, axis=0)

array([4.10276, 6.48112, 5.75436, 2.9186 , 4.97342, 5.31384])

- 각 열의 최솟값

In [46]:
np.min(x, axis=0)

array([2.3461, 0.7351, 2.0686, 0.1313, 2.204 , 2.1008])

- 정렬(sort)

In [48]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [49]:
np.sort(a)      # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [50]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [52]:
# 내림차순 정렬, axis=1인 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [55]:
# 내림차순 정렬, axis=0인 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [56]:
# sort()는 자기 파괴적(in-place) method
a.sort(axis=1)

In [57]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [62]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [63]:
a[j]

array([12, 25, 38, 42])

- 연습 문제 3.3.2

다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

In [104]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])


In [126]:
# 영어점수열 가장큰수가 마지막으로 가게 오름차순으로 재정렬하게만드는 인덱스값
j = np.argsort(a, axis=1)[1]
j

array([0, 3, 1, 2], dtype=int64)

In [124]:
# 그 인덱스값으로 모든행을 재정렬 ex. 인덱스값 2번인 3, 100, 90의값이 위의 순서대로 마지막인덱스로옮겨짐
a[:,j]  

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])