### 1.3 배열의 연산(Operation)

In [2]:
import numpy as np

- 벡터화 연산

In [3]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [4]:
%%time
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i]

CPU times: total: 46.9 ms
Wall time: 47 ms


In [5]:
%time z = x + y

CPU times: total: 0 ns
Wall time: 1e+03 µs


In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [7]:
a >= b

array([False,  True,  True,  True])

In [8]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [9]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [10]:
5 * a

array([ 5, 10, 15, 20])

In [11]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [12]:
x = np.arange(1, 5)
np.sum(x)

10

In [13]:
x.sum()

10

In [14]:
x.min(), x.max(), x.mean()          # 최소, 최대, 평균

(1, 4, 2.5)

In [15]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [16]:
# 통계: 분산, 표준편차
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [17]:
# 최소값, 최대값의 인덱스
x.argmin(), x.argmax()

(0, 3)

- all / any

In [18]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [19]:
np.all(a == a)

True

- 2차원 이상의 연산

In [20]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 모든 원소의 합과 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [22]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 액세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [23]:
# axis = 1, 각 좌표(row, col)에서 col를 변경시켜가면서 액세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [24]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [26]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [27]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [28]:
np.random.seed(2023)
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[7.7396, 7.4267, 0.7889, 7.74  , 2.3198, 2.0334],
       [9.6139, 8.084 , 5.1176, 8.0368, 6.8585, 2.5113],
       [4.4759, 9.431 , 6.3952, 6.3111, 0.1547, 9.7618],
       [1.7697, 3.9002, 0.3988, 4.3957, 9.0654, 3.417 ],
       [4.1365, 0.7397, 9.4343, 6.4918, 2.0729, 8.3916]])

- 전체의 최댓값

In [29]:
np.max(x)

9.7618

- 각 행의 합

In [30]:
np.sum(x, axis=1)

array([28.0484, 40.2221, 36.5297, 22.9468, 31.2668])

- 각 행의 최댓값

In [31]:
np.max(x, axis=1)[1]

9.6139

- 각 열의 평균

In [32]:
np.mean(x, axis=0)

array([5.54712, 5.91632, 4.42696, 6.59508, 4.09426, 5.22302])

- 각 열의 최솟값

In [33]:
np.min(x, axis=0)

array([1.7697, 0.7397, 0.3988, 4.3957, 0.1547, 2.0334])

- 정렬(sort)

In [34]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [35]:
np.sort(a)      # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [36]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [37]:
# 내림차순 정렬, axis=1인 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [38]:
# 내림차순 정렬, axis=0인 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [39]:
# sort()는 자기 파괴적(in-place) method
a.sort(axis=1)

In [40]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [41]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [42]:
a[j]

array([12, 25, 38, 42])

- 연습 문제 3.3.2

다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

In [43]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])


In [44]:
# 영어점수열 가장큰수가 마지막으로 가게 오름차순으로 재정렬하게만드는 인덱스값
j = np.argsort(a, axis=1)[1]
j

array([0, 3, 1, 2], dtype=int64)

In [45]:
# 그 인덱스값으로 모든행을 재정렬 ex. 인덱스값 2번인 3, 100, 90의값이 위의 순서대로 마지막인덱스로옮겨짐
a[:,j]  

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [46]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])


In [48]:
# 영어 성적을 argsort() 하여 인덱스를 구함
indices = np.argsort(a[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [50]:
# 인덱스를 내림차순으로 정렬
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [52]:
# 모든 행을 영어성적 내림차순으로 정렬
a[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [53]:
# 한 줄로
a[:, np.argsort(a[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])