### 1.5 난수 발생과 카운팅

In [1]:
import numpy as np

- 시드 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [4]:
x = np.arange(10)
np.random.shuffle(x)    # x 데이터의 순서를 바꿈
x

array([4, 6, 5, 3, 2, 8, 9, 7, 0, 1])

- 데이터의 샘플링

In [6]:
np.random.choice(5, 5, replace=False)   # 비복원 추출

array([1, 3, 0, 2, 4])

In [7]:
np.random.choice(5, 5, replace=True)    # 복원 추출

array([4, 1, 4, 1, 2])

In [8]:
x = np.random.randint(1, 100, 10)       # 1 <= x < 100
x

array([50, 78, 92, 88, 46, 35, 35, 12,  2, 32])

In [9]:
np.random.choice(x, 5, replace=False)

array([92, 35, 46, 78, 12])

- 난수 생성

In [10]:
# random() - Uniform 분포, 0 ~ 1 사이의 값 N개
np.random.random(10)

array([0.58847827, 0.63320608, 0.24210542, 0.67288497, 0.36779874,
       0.70890545, 0.29661228, 0.76426994, 0.74813731, 0.69862951])

In [11]:
# randint(low, high, N) - [low, high) 범위의 정수 N개
np.random.randint(1, 7, 10)

array([6, 3, 6, 6, 3, 2, 3, 3, 1, 5])

In [12]:
# normal(평균, 표준편차, N) - 정규분포 N개
np.random.normal(170, 10, 10)

array([169.99914394, 177.58645897, 167.26943945, 147.39058082,
       172.02856304, 170.06243698, 163.02103652, 183.17999901,
       156.694853  , 188.43338852])

In [13]:
# randn - 표준정규분포 N(0, 1) N 개
np.random.randn(10)

array([ 0.07586461, -0.88877486,  0.72900879,  0.17879745,  0.79162212,
       -0.51695485, -0.39389091,  0.04087316,  0.66214703, -2.02396848])

In [14]:
# binomial(시도횟수, 평균, N) - 이항분포 N개
np.random.binomial(10, 0.5, 20).reshape(4, 5)

array([[2, 6, 4, 6, 6],
       [4, 6, 5, 7, 5],
       [5, 5, 6, 3, 6],
       [7, 5, 6, 5, 8]])

In [15]:
# 가설검정: t-검정 (1-sample T, 2-sample T, paired T)
# Student t(자유도, N)
np.random.standard_t(2, 10)

array([ 2.47395645, -1.38920435, -0.87036697,  0.37764753, -1.24874601,
       -0.56429419, -1.74308619, -0.00891616, -0.18602028, -0.29526812])

- 연습문제 3.5.1

In [20]:
# 1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(2, 0.5, 10)

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1])

In [24]:
# 2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
np.mean(np.random.randint(1, 7, 100))

3.39

- 연습문제 3.5.2

In [28]:
# 5개만 먼저 테스트
rate = np.random.normal(0, 0.01, 5)
rate

array([ 0.01277624,  0.01359915,  0.01142813, -0.00368581, -0.00549472])

In [30]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])    # price * (1 + r)
    price = int(round(price, 0))     # 가격의 단위는 원(소수점 아래 자리는 버림)
    print(price, end=' ')

10128 10266 10383 10345 10288 

In [33]:
# 100개의 수익률 생성
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [34]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0))
    price_list.append(price)

price_list[-10:]        # 어레이로 만들고 싶으면    np.array(price_list)

[10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691, 10497]

In [35]:
# 2. 어레이로 해결
price = 10000
price_array = np.empty(250, dtype= int)
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0))
    price_array[i] = price

price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [39]:
np.random.seed(2023)
dices = np.random.randint(1, 7, 100)

In [40]:
# 고유한 값
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [41]:
# 고유한 값과 돗수
np.unique(dices, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([16, 18, 13, 15, 19, 19], dtype=int64))

In [42]:
indices, count = np.unique(dices, return_counts=True)
indices * count

array([ 16,  36,  39,  60,  95, 114], dtype=int64)

In [43]:
# 가중 평균
np.sum(indices * count) / np.sum(count)

3.6

In [44]:
np.mean(dices)

3.6

In [45]:
a = np.array(['x', 'y', 'x', 'y', 'z', 'y'])
np.unique(a, return_counts=True)

(array(['x', 'y', 'z'], dtype='<U1'), array([2, 3, 1], dtype=int64))